[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "server"
path = "src/lib.rs"

[[bin]]
name = "simple_rdbms_server"
path = "src/main.rs"

[dependencies]
common = { workspace = true }
engine = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
ctrlc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
